#######

# Valid request

#POST https://nh3mp4cs87.execute-api.eu-west-1.amazonaws.com/prod/request
POST https://task.perf-mon.examples.oleksiipopov.com/request
Content-Type: application/json

{
  "projectName": "ExampleProject",
  "baseUrl": "https://example.com",
  "environment": "production",
  "gitBranchOrTag": "main",
  "urls": [
    {
      "shortPageName": "HomePage",
      "url": "https://example.com/home",
      "iterations": 5,
      "browsers": ["chrome", "firefox"]
    },
    {
      "shortPageName": "ContactPage",
      "url": "https://example.com/contact",
      "iterations": 3,
      "browsers": ["chrome"]
    }
  ]
}

#######

# Invalid JSON payload

POST https://task.perf-mon.examples.oleksiipopov.com/request
Content-Type: application/json

{bla}

######

# Validation error

POST https://task.perf-mon.examples.oleksiipopov.com/request
Content-Type: application/json

{
  "projectName": "ExampleProject",
  "baseUrl": "https://example.com"
}