#######

# Valid simple single request

POST https://task.perf-mon.examples.oleksiipopov.com/request
Content-Type: application/json

{
  "projectName": "ExampleProject",
  "baseUrl": "https://oleksiipopov.com",
  "environment": "production",
  "gitBranchOrTag": "main",
  "variants": [
    {
      "variantName": "ContactPage",
      "urls": [
        "https://oleksiipopov.com/contact"
      ],
      "iterations": 3,
      "browsers": ["chrome"]
    }
  ]
}


#######

# Valid request

POST https://task.perf-mon.examples.oleksiipopov.com/request
Content-Type: application/json

{
  "projectName": "ExampleProject",
  "baseUrl": "https://oleksiipopov.com",
  "environment": "production",
  "gitBranchOrTag": "main",
  "variants": [
    {
      "variantName": "HomePage",
      "urls": [
        "https://oleksiipopov.com/"
      ],
      "iterations": 5,
      "browsers": ["chrome", "firefox"]
    },
    {
      "variantName": "ContactPage",
      "urls": [
        "https://oleksiipopov.com/contact"
      ],
      "iterations": 3,
      "browsers": ["chrome"]
    }
  ]
}

#######

# Invalid JSON payload

POST https://task.perf-mon.examples.oleksiipopov.com/request
Content-Type: application/json

{bla}

######

# Validation error

POST https://task.perf-mon.examples.oleksiipopov.com/request
Content-Type: application/json

{
  "projectName": "ExampleProject",
  "baseUrl": "https://oleksiipopov.com"
}