#######

# Valid simple single request

POST https://task.perf-mon.examples.oleksiipopov.com/request
Content-Type: application/json

{
  "projectName": "ExampleProject",
  "baseUrl": "https://oleksiipopov.com",
  "environment": "production",
  "gitBranchOrTag": "main",
  "variants": [
    {
      "variantName": "ContactPage",
      "urls": [
        "https://oleksiipopov.com/contact/?silent"
      ],
      "iterations": 1,
      "browsers": ["chrome"]
    }
  ]
}


#######

# Valid request

POST https://task.perf-mon.examples.oleksiipopov.com/request
Content-Type: application/json

{
  "projectName": "ExampleProject",
  "baseUrl": "https://oleksiipopov.com",
  "environment": "production",
  "gitBranchOrTag": "main",
  "variants": [
    {
      "variantName": "Home",
      "urls": [
        "https://oleksiipopov.com/?silent"
      ],
      "iterations": 3,
      "browsers": ["chrome", "firefox"]
    },
    {
      "variantName": "Contact",
      "urls": [
        "https://oleksiipopov.com/contact/?silent"
      ],
      "iterations": 3,
      "browsers": ["chrome"]
    },
    {
      "variantName": "Article_Project",
      "urls": [
        "https://oleksiipopov.com/blog/react-18-vs-react-19/?silent",
        "https://oleksiipopov.com/portfolio/tomtom-web-sdk-demo-catalog/?silent"
      ],
      "iterations": 3,
      "browsers": ["chrome"]
    },
    {
      "variantName": "Blog_Portfolio",
      "urls": [
        "https://oleksiipopov.com/blog/?silent",
        "https://oleksiipopov.com/portfolio/?silent"
      ],
      "iterations": 3,
      "browsers": ["chrome"]
    },
    {
      "variantName": "Resume",
      "urls": [
        "https://oleksiipopov.com/resume/?silent"
      ],
      "iterations": 3,
      "browsers": ["chrome"]
    }
  ]
}

#######

# Invalid JSON payload

POST https://task.perf-mon.examples.oleksiipopov.com/request
Content-Type: application/json

{bla}

######

# Validation error

POST https://task.perf-mon.examples.oleksiipopov.com/request
Content-Type: application/json

{
  "projectName": "ExampleProject",
  "baseUrl": "https://oleksiipopov.com"
}