name: Legacy Cloud pipeline (deprecated)

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/cloud.yml'  # Only trigger for this specific file

env:
  DEFAULT_BRANCH: main
  AWS_ACCOUNT: ${{ vars.AWS_ACCOUNT }}
  AWS_DEPLOYMENT_REGION: ${{ vars.AWS_DEPLOYMENT_REGION }}
  HOSTED_ZONE_ID: ${{ vars.HOSTED_ZONE_ID }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Prepare variables
        run: echo SAFE_SOURCE_NAME=$(echo "${{ github.ref_name }}" | sed -r 's/[/.@_]+/-/g') >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install runtime
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install, type-check, lint, and test
        run: |
          pnpm install --frozen-lockfile
          pnpm run build
          pnpm test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ vars.AWS_AUTH_ROLE }}

      - name: Deploy infrastructure
        if: env.SAFE_SOURCE_NAME == env.DEFAULT_BRANCH
        run: pnpm --filter @web-perf-mon/infrastructure cdk deploy --all --require-approval never
        env:
          GRAPHITE_AUTH: ${{ secrets.GRAPHITE_AUTH }}
          IDLE_MODE: ${{ vars.IDLE_MODE }}
          API_KEY: ${{ secrets.API_KEY }}

      - name: Diff infrastructure
        if: env.SAFE_SOURCE_NAME != env.DEFAULT_BRANCH
        run: pnpm --filter @web-perf-mon/infrastructure cdk diff
        env:
          GRAPHITE_AUTH: ${{ secrets.GRAPHITE_AUTH }}
          IDLE_MODE: ${{ vars.IDLE_MODE }}
          API_KEY: ${{ secrets.API_KEY }}