name: Infrastructure Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'packages/infrastructure/**'
      - 'packages/shared/**'
      - 'pnpm-workspace.yaml'
      - 'package.json'

env:
  DEFAULT_BRANCH: main
  AWS_ACCOUNT: ${{ vars.AWS_ACCOUNT }}
  AWS_DEPLOYMENT_REGION: ${{ vars.AWS_DEPLOYMENT_REGION }}
  HOSTED_ZONE_ID: ${{ vars.HOSTED_ZONE_ID }}

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install runtime
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build shared package and infrastructure
        run: |
          pnpm --filter @web-perf-mon/shared build
          pnpm --filter @web-perf-mon/infrastructure build
          pnpm --filter @web-perf-mon/infrastructure test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ vars.AWS_AUTH_ROLE }}

      - name: Deploy infrastructure
        run: pnpm --filter @web-perf-mon/infrastructure cdk deploy --all --require-approval never
        env:
          GRAPHITE_AUTH: ${{ secrets.GRAPHITE_AUTH }}
          IDLE_MODE: ${{ vars.IDLE_MODE }}
          API_KEY: ${{ secrets.API_KEY }}

      - name: Save CDK outputs
        run: |
          pnpm --filter @web-perf-mon/infrastructure cdk list --json > cdk-outputs.json
          echo "Infrastructure deployed successfully"